/* Candy Rope — swipe to cut ropes so the candy swings, floats and drops into the hungry frog. Levels are generated by
   simulating a solution first, so every level is solvable and the stars sit on a reachable path. */
(function () {
  const K = window.Kit;
  K.fontFamily = '"Trebuchet MS", "Segoe UI", sans-serif';
  const LW = 600, LH = 900, DT = 1 / 60, SEG = 22, GRAV = 1300, LEVELS = 45;

  K.boot('candy_rope', { g: { lvl: 0, stars: {} } }, main);

  function main() {
    const G = K.save.data.g;
    const cv = document.getElementById('c'), ctx = cv.getContext('2d');
    let W = 0, H = 0, DPR = 1, sc = 1, ox = 0, oy = 0;
    const toS = (x, y) => ({ x: ox + x * sc, y: oy + y * sc });

    /* ---------- deterministic world ---------- */
    function makeWorld(def) {
      const w = { pts: [], ropes: [], candy: null, bubbles: def.bubbles.map((b) => ({ ...b, on: false, popped: false })), autos: def.autos.map((a) => ({ ...a, used: false })), pins: def.pins.slice(), t: 0 };
      const c = { x: def.candy[0], y: def.candy[1], px: def.candy[0] - (def.kick || 0), py: def.candy[1], m: 3 };
      w.candy = c; w.pts.push(c);
      def.pins.forEach((p) => addRope(w, p));
      return w;
    }
    function addRope(w, p) {
      const c = w.candy, len = Math.hypot(c.x - p.x, c.y - p.y) * (p.slack || 1.02), n = Math.max(3, Math.round(len / SEG));
      const chain = [{ x: p.x, y: p.y, px: p.x, py: p.y, pin: true }];
      for (let k = 1; k < n; k++) { const t = k / n; const q = { x: K.lerp(p.x, c.x, t), y: K.lerp(p.y, c.y, t) }; q.px = q.x; q.py = q.y; chain.push(q); }
      chain.push(c);
      w.ropes.push({ chain, rest: len / n, cut: -1, pin: p });
    }
    function step(w) {
      w.t += DT;
      const c = w.candy, lift = w.bubbles.some((b) => b.on && !b.popped);
      const all = new Set([c]); w.ropes.forEach((r) => r.chain.forEach((q) => all.add(q)));
      all.forEach((q) => { if (q.pin) return; const vx = (q.x - q.px) * 0.995, vy = (q.y - q.py) * 0.995; q.px = q.x; q.py = q.y; q.x += vx; q.y += vy + (q === c && lift ? -GRAV * 0.35 : GRAV) * DT * DT; });
      for (let it = 0; it < 12; it++) w.ropes.forEach((r) => { for (let k = 0; k < r.chain.length - 1; k++) { if (k === r.cut) continue; const a = r.chain[k], b = r.chain[k + 1], dx = b.x - a.x, dy = b.y - a.y, d = Math.hypot(dx, dy) || 1, diff = (d - r.rest) / d; if (d < r.rest) continue; const wa = a.pin ? 0 : b === c ? 0.85 : 0.5, wb = b.pin ? 0 : b === c ? 0.15 : 0.5; a.x += dx * diff * wa; a.y += dy * diff * wa; b.x -= dx * diff * wb; b.y -= dy * diff * wb; } });
      // bubbles catch the candy
      w.bubbles.forEach((b) => { if (!b.on && !b.popped && Math.hypot(c.x - b.x, c.y - b.y) < 45) { b.on = true; if (w.onEvent) w.onEvent('bubble'); } if (b.on && !b.popped) { b.x = c.x; b.y = c.y; } });
      if (lift) { c.px = K.lerp(c.px, c.x, 0.03); }
      w.autos.forEach((a) => { if (!a.used && Math.hypot(c.x - a.x, c.y - a.y) < a.r) { a.used = true; addRope(w, { x: a.x, y: a.y, slack: 1 }); if (w.onEvent) w.onEvent('auto'); } });
    }
    function cutRope(w, r, k) { if (r.cut >= 0) return false; r.cut = k; return true; }
    /* ---------- level generation by simulating a solution ---------- */
    function genLevel(i) {
      const r = K.rng(i * 1009 + 71), tpl0 = i < 4 ? 0 : i < 10 ? i % 2 : Math.floor(r() * 4);
      for (let tries = 0; tries < 240; tries++) {
        const tpl = tries < 160 ? tpl0 : tries % 2;
        const def = { pins: [], bubbles: [], autos: [], candy: null, kick: 0 }, sol = [];
        if (tpl === 0) { const px = 150 + r() * 300; def.pins.push({ x: px, y: 120 }); def.candy = [px + (r() - 0.5) * 300, 360 + r() * 80]; sol.push({ t: 0.4 + r() * 1.4, rope: 0 }); }
        else if (tpl === 1) { def.pins.push({ x: 90, y: 150 + r() * 100 }, { x: 510, y: 150 + r() * 100 }); def.candy = [200 + r() * 200, 360]; const first = r() < 0.5 ? 0 : 1; sol.push({ t: 0.5 + r() * 0.6, rope: first }); sol.push({ t: 1.4 + r() * 1.2, rope: 1 - first }); }
        else if (tpl === 2) { const px = 150 + r() * 300; def.pins.push({ x: px, y: 380 }); def.candy = [px + (r() - 0.5) * 200, 560]; def.bubbles.push({ x: def.candy[0] + (r() - 0.5) * 40, y: 700 }); sol.push({ t: 0.3 + r() * 0.8, rope: 0 }); sol.push({ t: 2.6 + r() * 1.4, pop: 0 }); }
        else { def.pins.push({ x: 300 + (r() - 0.5) * 300, y: 110 }); def.candy = [def.pins[0].x + (r() - 0.5) * 240, 280]; def.autos.push({ x: 150 + r() * 300, y: 380 + r() * 140, r: 95 }); sol.push({ t: 0.5 + r() * 1.2, rope: 0 }); sol.push({ t: 2.2 + r() * 1.6, rope: 1 }); }
        const w = makeWorld(def), path = []; let si = 0, ok = false, end = null;
        for (let f = 0; f < 60 * 9; f++) {
          while (si < sol.length && w.t >= sol[si].t) { const s = sol[si++]; if (s.rope != null) { const rope = w.ropes[s.rope === 2 ? w.ropes.length - 1 : s.rope]; if (rope) cutRope(w, rope, 1); } if (s.pop != null) w.bubbles[s.pop].popped = true; }
          step(w); path.push([w.candy.x, w.candy.y]);
          const c = w.candy;
          if (si >= sol.length && c.y > 620 && c.y < 800 && c.x > 70 && c.x < 530 && c.y - c.py > 1) { end = [c.x, c.y + 20]; ok = true; break; }
          if (c.x < -50 || c.x > LW + 50 || c.y > LH + 50 || c.y < -100) break;
        }
        if (!ok) continue;
        const L = path.length, stars = [0.35, 0.6, 0.85].map((k) => { const p = path[Math.floor(L * k)]; return { x: p[0], y: p[1], got: false }; });
        if (stars.some((s) => s.y < 40)) continue;
        const spikes = [];
        if (i > 6) for (let k = 0; k < Math.min(3, Math.floor(i / 8)); k++) { const sx = 60 + r() * 480, sy = 250 + r() * 500; if (path.every(([x, y]) => Math.hypot(x - sx, y - sy) > 90) && Math.hypot(end[0] - sx, end[1] - sy) > 120) spikes.push({ x: sx, y: sy, w: 110 }); }
        return { def, frog: end, stars, spikes, sol };
      }
      return { def: { pins: [{ x: 300, y: 120 }], bubbles: [], autos: [], candy: [300, 400] }, frog: [300, 720], stars: [{ x: 300, y: 500 }, { x: 300, y: 560 }, { x: 300, y: 620 }], spikes: [], sol: [] };
    }

    /* ---------- play ---------- */
    let L = null, world = null, lvIdx = 0, playing = false, got = 0, acc = 0, swipe = [], state = 'play', frogMouth = 0, eatT = 0, hintOn = false;
    function startLevel(i) {
      lvIdx = i; L = genLevel(i); world = makeWorld(L.def); world.onEvent = (e) => K.audio.play(e === 'bubble' ? 'pop' : 'swing', 1.3);
      L.stars.forEach((s) => (s.got = false)); got = 0; state = 'play'; playing = true; hintOn = false; eatT = 0;
      K.std.hideMenu(); hud.style.display = bar.style.display = ''; K.game.start();
    }
    function checkCut(a, b) {
      for (const r of world.ropes) { if (r.cut >= 0) continue; for (let k = 0; k < r.chain.length - 1; k++) { const p = r.chain[k], q = r.chain[k + 1]; if (segX(a, b, p, q)) { cutRope(world, r, k); K.audio.play('swing', 1.6); K.meta.track('cuts', 1); const s = toS(p.x, p.y); K.fx.burst(s.x, s.y, { n: 6, colors: ['#c9a27e', '#fff'], speed: 120, size: 3, life: 0.4 }); break; } } }
      // popping bubbles by swipe or tap
      world.bubbles.forEach((bb) => { if (bb.on && !bb.popped && distSeg(bb, a, b) < 45) { bb.popped = true; K.audio.play('pop', 0.8); const s = toS(bb.x, bb.y); K.fx.burst(s.x, s.y, { n: 14, colors: ['#bde0fe', '#fff'], speed: 200, size: 4, life: 0.4 }); } });
    }
    const ccw = (a, b, c) => (c.y - a.y) * (b.x - a.x) > (b.y - a.y) * (c.x - a.x);
    const segX = (a, b, c, d) => ccw(a, c, d) !== ccw(b, c, d) && ccw(a, b, c) !== ccw(a, b, d);
    const distSeg = (p, a, b) => { const dx = b.x - a.x, dy = b.y - a.y, t = K.clamp(((p.x - a.x) * dx + (p.y - a.y) * dy) / (dx * dx + dy * dy || 1), 0, 1); return Math.hypot(p.x - a.x - dx * t, p.y - a.y - dy * t); };
    function update(dt) {
      if (!playing || state !== 'play') return;
      acc += dt;
      while (acc >= DT) {
        acc -= DT; step(world);
        const c = world.candy;
        L.stars.forEach((s) => { if (!s.got && Math.hypot(c.x - s.x, c.y - s.y) < 34) { s.got = true; got++; K.audio.play('coin', 1 + got * 0.15); K.meta.track('stars', 1); const q = toS(s.x, s.y); K.fx.burst(q.x, q.y, { n: 16, colors: ['#ffd166', '#fff'], speed: 220, shape: 'star', size: 6, life: 0.6 }); } });
        if (L.spikes.some((sp) => c.x > sp.x - sp.w / 2 && c.x < sp.x + sp.w / 2 && Math.abs(c.y - sp.y) < 20)) return lose(K.t(['The candy broke on the spikes!', 'O doce quebrou nos espinhos!']));
        if (Math.hypot(c.x - L.frog[0], c.y - (L.frog[1] - 10)) < 48) return win();
        if (c.x < -60 || c.x > LW + 60 || c.y > LH + 60 || c.y < -200) return lose(K.t(['The candy got away!', 'O doce escapou!']));
      }
    }
    function win() {
      state = 'eat'; eatT = 0; K.audio.play('merge', 0.6); K.audio.play('win'); K.game.happy();
      const stars = got; G.stars[lvIdx] = Math.max(G.stars[lvIdx] || 0, stars); if (lvIdx === G.lvl && G.lvl < LEVELS - 1) G.lvl++;
      K.meta.track('levels', 1); K.meta.addXp(12); K.save.mark();
      setTimeout(() => { playing = false; K.std.end({ win: true, title: K.t(['Yum!', 'Nhami!']), text: '★'.repeat(stars) + '☆'.repeat(3 - stars), coins: 20 + lvIdx * 4 + stars * 12, mult: 3, next: { fn: () => startLevel(G.lvl) }, restart: () => startLevel(lvIdx), menu: showMenu }); }, 1200);
    }
    function lose(text) { state = 'lost'; playing = false; K.game.stop(); K.audio.play('lose'); setTimeout(() => K.std.end({ text, coins: 0, revive: () => { hintOn = true; startLevel(lvIdx); hintOn = true; }, reviveLabel: K.t(['Show solution', 'Mostrar solução']), restart: () => startLevel(lvIdx), menu: showMenu }), 500); }
    cv.addEventListener('pointerdown', (e) => { swipe = [{ x: (e.clientX - ox) / sc, y: (e.clientY - oy) / sc, t: 0 }]; });
    window.addEventListener('pointermove', (e) => { if (!swipe.length || !playing) return; const p = { x: (e.clientX - ox) / sc, y: (e.clientY - oy) / sc, t: 0 }; checkCut(swipe[swipe.length - 1], p); swipe.push(p); if (swipe.length > 12) swipe.shift(); });
    window.addEventListener('pointerup', (e) => { if (swipe.length === 1 && playing) { const p = swipe[0]; world.bubbles.forEach((bb) => { if (bb.on && !bb.popped && Math.hypot(bb.x - p.x, bb.y - p.y) < 50) { bb.popped = true; K.audio.play('pop', 0.8); } }); } swipe = []; });

    K.meta.init({
      coinScale: () => 1,
      howTo: { en: 'Swipe across a rope to cut it. Swing the candy so it falls into the frog’s mouth, grabbing the stars on the way. Tap a bubble to pop it. Avoid the thorny vines.', pt: 'Deslize sobre uma corda para cortá-la. Balance o doce para ele cair na boca do sapo, pegando as estrelas no caminho. Toque na bolha para estourar. Evite os espinhos.' },
      missions: [{ stat: 'stars', base: 12, reward: 80, text: { en: 'Collect {n} stars', pt: 'Pegue {n} estrelas' } }, { stat: 'levels', base: 4, reward: 110, text: { en: 'Feed the frog {n} times', pt: 'Alimente o sapo {n} vezes' } }, { stat: 'cuts', base: 20, reward: 60, text: { en: 'Cut {n} ropes', pt: 'Corte {n} cordas' } }],
    });
    K.meta.buildHud({});
    const hud = K.el('div', 'kit-hud'); K.ui.root.appendChild(hud);
    const bar = K.el('div', 'crbar'); K.ui.root.appendChild(bar);
    bar.appendChild(K.ui.btn('⟲', 'sm', () => startLevel(lvIdx)));
    bar.appendChild(K.ui.adBtn('💡', () => { hintOn = true; startLevel(lvIdx); hintOn = true; }, 'sm'));
    bar.appendChild(K.ui.btn('⌂', 'sm', showMenu));
    function showMenu() {
      playing = false; hud.style.display = bar.style.display = 'none';
      K.std.menu({ title: 'Candy<span>Rope</span>', sub: K.t('level') + ' ' + (G.lvl + 1) + ' / ' + LEVELS, onPlay: () => startLevel(G.lvl), buttons: [K.ui.btn('▦ ' + K.t(['Levels', 'Fases']), '', () => K.std.levels(K.t(['Levels', 'Fases']), LEVELS, G.lvl, G.stars, (i) => { K.std.hideMenu(); startLevel(i); }))] });
      if (!L) { L = genLevel(G.lvl); world = makeWorld(L.def); }
    }
    function drawFrog(x, y, open) {
      const s = toS(x, y), u = sc;
      ctx.save(); ctx.translate(s.x, s.y);
      ctx.fillStyle = '#7a5c3c'; ctx.beginPath(); ctx.ellipse(0, 36 * u, 70 * u, 16 * u, 0, 0, 6.283); ctx.fill(); // lily/log
      ctx.fillStyle = '#6ab04c'; ctx.beginPath(); ctx.ellipse(0, 10 * u, 52 * u, 38 * u, 0, 0, 6.283); ctx.fill();
      ctx.fillStyle = '#badc58'; ctx.beginPath(); ctx.ellipse(0, 22 * u, 34 * u, 20 * u, 0, 0, 6.283); ctx.fill();
      for (const sx of [-1, 1]) { ctx.fillStyle = '#6ab04c'; ctx.beginPath(); ctx.arc(sx * 24 * u, -22 * u, 16 * u, 0, 6.283); ctx.fill(); ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.arc(sx * 24 * u, -24 * u, 11 * u, 0, 6.283); ctx.fill(); const cx = world ? K.clamp((world.candy.x - x) / 200, -1, 1) * 4 : 0, cy = world ? K.clamp((world.candy.y - y) / 200, -1, 1) * 4 : 0; ctx.fillStyle = '#1d1d1d'; ctx.beginPath(); ctx.arc(sx * 24 * u + cx * u, -24 * u + cy * u, 5 * u, 0, 6.283); ctx.fill(); }
      ctx.fillStyle = '#c0392b'; ctx.beginPath(); ctx.ellipse(0, 4 * u, 30 * u, (4 + open * 22) * u, 0, 0, 6.283); ctx.fill();
      if (open > 0.5) { ctx.fillStyle = '#ff7b8a'; ctx.beginPath(); ctx.ellipse(0, 10 * u + open * 6 * u, 14 * u, 6 * u, 0, 0, 6.283); ctx.fill(); }
      ctx.restore();
    }
    let tt = 0;
    K.loop((dt) => { tt += dt; update(dt); K.fx.update(dt); if (state === 'eat') eatT += dt; if (playing) hud.innerHTML = `<span class="chip">${K.t('level')} ${lvIdx + 1}</span><span class="chip">${'★'.repeat(got)}${'☆'.repeat(3 - got)}</span>`; }, () => {
      ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
      const gr = ctx.createLinearGradient(0, 0, 0, H); gr.addColorStop(0, '#fbe7c6'); gr.addColorStop(1, '#b4f8c8'); ctx.fillStyle = gr; ctx.fillRect(0, 0, W, H);
      // cardboard box frame
      ctx.fillStyle = '#e8c8a0'; ctx.fillRect(ox - 10, oy - 10, LW * sc + 20, LH * sc + 20); ctx.fillStyle = '#fff6e5'; ctx.fillRect(ox, oy, LW * sc, LH * sc);
      ctx.strokeStyle = 'rgba(160,120,80,.12)'; ctx.lineWidth = 1; for (let y = 0; y < LH; y += 30) { const a = toS(0, y), b = toS(LW, y); ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); }
      if (!world) return;
      ctx.save(); ctx.translate(K.fx.shakeX, K.fx.shakeY);
      // hint path
      if (hintOn) { const w2 = makeWorld(L.def); let si = 0; ctx.fillStyle = 'rgba(255,120,0,.35)'; for (let f = 0; f < 60 * 6; f++) { while (si < L.sol.length && w2.t >= L.sol[si].t) { const s = L.sol[si++]; if (s.rope != null) { const rope = w2.ropes[s.rope === 2 ? w2.ropes.length - 1 : s.rope]; if (rope) cutRope(w2, rope, 1); } if (s.pop != null) w2.bubbles[s.pop].popped = true; } step(w2); if (f % 5 === 0) { const q = toS(w2.candy.x, w2.candy.y); ctx.beginPath(); ctx.arc(q.x, q.y, 4, 0, 6.283); ctx.fill(); } } ctx.fillStyle = '#ff7b00'; ctx.font = '700 14px sans-serif'; L.sol.forEach((s, k) => { const q = toS(40, 60 + k * 20); ctx.fillText(`${k + 1}. ${s.pop != null ? K.t(['pop bubble', 'estourar bolha']) : K.t(['cut rope', 'cortar corda'])} @ ${s.t.toFixed(1)}s`, q.x, q.y); }); }
      L.spikes.forEach((sp) => { const a = toS(sp.x - sp.w / 2, sp.y); ctx.fillStyle = '#4a6b3a'; ctx.fillRect(a.x, a.y - 6 * sc, sp.w * sc, 12 * sc); ctx.fillStyle = '#2d4a22'; for (let k = 0; k < sp.w / 12; k++) { ctx.beginPath(); ctx.moveTo(a.x + k * 12 * sc, a.y - 6 * sc); ctx.lineTo(a.x + (k * 12 + 6) * sc, a.y - 18 * sc); ctx.lineTo(a.x + (k + 1) * 12 * sc, a.y - 6 * sc); ctx.fill(); ctx.beginPath(); ctx.moveTo(a.x + k * 12 * sc, a.y + 6 * sc); ctx.lineTo(a.x + (k * 12 + 6) * sc, a.y + 18 * sc); ctx.lineTo(a.x + (k + 1) * 12 * sc, a.y + 6 * sc); ctx.fill(); } });
      world.autos.forEach((a) => { const s = toS(a.x, a.y); ctx.strokeStyle = a.used ? 'rgba(0,0,0,.1)' : 'rgba(255,123,0,.5)'; ctx.setLineDash([6, 6]); ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(s.x, s.y, a.r * sc, 0, 6.283); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle = '#ff7b00'; ctx.beginPath(); ctx.arc(s.x, s.y, 8 * sc, 0, 6.283); ctx.fill(); });
      L.stars.forEach((st) => { if (st.got) return; const s = toS(st.x, st.y); ctx.save(); ctx.translate(s.x, s.y); ctx.rotate(Math.sin(tt * 2 + st.x) * 0.3); ctx.fillStyle = '#ffd166'; K.draw.star(ctx, 0, 0, 20 * sc, 9 * sc, 5); ctx.fill(); ctx.strokeStyle = '#e09f3e'; ctx.lineWidth = 2; ctx.stroke(); ctx.restore(); });
      drawFrog(L.frog[0], L.frog[1], state === 'eat' ? Math.max(0, 1 - eatT * 2) : world ? K.clamp(1 - Math.hypot(world.candy.x - L.frog[0], world.candy.y - L.frog[1]) / 250, 0, 1) : 0);
      // ropes
      world.ropes.forEach((r) => { ctx.strokeStyle = '#8d6e63'; ctx.lineWidth = 4 * sc; ctx.lineCap = 'round'; for (let k = 0; k < r.chain.length - 1; k++) { if (k === r.cut) continue; const a = toS(r.chain[k].x, r.chain[k].y), b = toS(r.chain[k + 1].x, r.chain[k + 1].y); ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke(); } const p = toS(r.pin.x, r.pin.y); ctx.fillStyle = '#6d4c41'; ctx.beginPath(); ctx.arc(p.x, p.y, 9 * sc, 0, 6.283); ctx.fill(); ctx.fillStyle = '#d7ccc8'; ctx.beginPath(); ctx.arc(p.x, p.y, 4 * sc, 0, 6.283); ctx.fill(); });
      world.pins.forEach((p) => { const s = toS(p.x, p.y); ctx.fillStyle = '#6d4c41'; ctx.beginPath(); ctx.arc(s.x, s.y, 9 * sc, 0, 6.283); ctx.fill(); });
      world.bubbles.forEach((b) => { if (b.popped) return; const s = toS(b.x, b.y); ctx.strokeStyle = 'rgba(100,170,255,.8)'; ctx.fillStyle = 'rgba(189,224,254,.35)'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(s.x, s.y, 42 * sc, 0, 6.283); ctx.fill(); ctx.stroke(); ctx.fillStyle = 'rgba(255,255,255,.7)'; ctx.beginPath(); ctx.arc(s.x - 14 * sc, s.y - 14 * sc, 8 * sc, 0, 6.283); ctx.fill(); });
      if (state !== 'eat' || eatT < 0.15) { const c = toS(world.candy.x, world.candy.y), r = 22 * sc; ctx.save(); ctx.translate(c.x, c.y); ctx.rotate(tt); ctx.fillStyle = '#ff5d8f'; ctx.beginPath(); ctx.moveTo(-r, 0); ctx.lineTo(-r * 1.7, -r * 0.6); ctx.lineTo(-r * 1.7, r * 0.6); ctx.fill(); ctx.beginPath(); ctx.moveTo(r, 0); ctx.lineTo(r * 1.7, -r * 0.6); ctx.lineTo(r * 1.7, r * 0.6); ctx.fill(); ctx.beginPath(); ctx.arc(0, 0, r, 0, 6.283); ctx.fill(); ctx.strokeStyle = '#fff'; ctx.lineWidth = 4 * sc; ctx.beginPath(); ctx.arc(0, 0, r * 0.6, 0.5, 4); ctx.stroke(); ctx.restore(); }
      // swipe trail
      if (swipe.length > 1) { ctx.strokeStyle = 'rgba(255,255,255,.9)'; ctx.lineWidth = 4; ctx.beginPath(); swipe.forEach((p, k) => { const s = toS(p.x, p.y); k ? ctx.lineTo(s.x, s.y) : ctx.moveTo(s.x, s.y); }); ctx.stroke(); }
      K.fx.draw(ctx); ctx.restore(); K.fx.drawFlash(ctx, W, H);
    });
    K.fit(cv, (w, h, d) => { W = w; H = h; DPR = d; sc = Math.min((w - 20) / LW, (h - 90) / LH); ox = (w - LW * sc) / 2; oy = 70 + (h - 80 - LH * sc) / 2; });
    K.debug = { genLevel };
    K.music.set({ bpm: 100, chords: [[64, 67, 71], [62, 65, 69], [60, 64, 67], [59, 62, 67]], pad: true, arp: [1, 0, 1, 0, 1, 0, 0, 1], arpWave: 'sine', bass: true, lead: [76, 0, 79, 0, 76, 0, 72, 0, 74, 0, 71, 0, 72, 0, 0, 0], leadWave: 'triangle' });
    showMenu();
  }
})();
